using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace MoreMountains.Tools
{
	/// <summary>
	/// A class used to display a reoderable list of MMTilemapGeneratorLayers
	/// </summary>
	[System.Serializable]
	public class MMTilemapGeneratorLayerList : MMReorderableArray<MMTilemapGeneratorLayer>
	{
	}
    
	/// <summary>
	/// A class used to store and edit the data of MMTilemapGenerator layers, which you can use and combine
	/// to generate unique and random grids
	/// </summary>
	[Serializable]
	public class MMTilemapGeneratorLayer
	{
		#if MM_PHYSICS2D
		/// the grid generated by this layer
		public virtual int[,] Grid { get; set; }
        
		/// the various modes of fusion you can use on this layer.
		/// Fusion modes will be applied on layers from top to bottom (the last to speak wins)
		/// Normal : just generates a grid, default mode
		/// NormalNoClear : generates a grid, but doesn't clear it first
		/// Intersect : when painting on a target grid that already has content, will only keep the resulting intersection
		/// Combine : adds the result of this grid to the existing target
		/// Subtract : removes the result of this grid from the existing target 
		public enum FusionModes { Normal, NormalNoClear, Intersect, Combine, Subtract }
        
		/// the name of this layer, doesn't do anything, just used to organize things
		[Tooltip("图层名称，仅用于组织与识别，不影响生成结果")]
		public string Name = "Layer";
		/// whether this layer should be taken into account when generating the final grid
		[Tooltip("该图层是否参与最终网格生成；关闭后此图层会被完全跳过")]
		public bool Active = true;
        
		[Header("Tilemaps")]
		/// the tilemap on which to paint tiles
		[Tooltip("该图层要绘制到的目标 Tilemap")]
		public Tilemap TargetTilemap;
		/// the tile to use to paint on the tilemap
		[Tooltip("邻近目标 瓷砖地图 时使用的 瓦")]
		public TileBase Tile;

		[Header("Grid")] 
		/// whether or not this layer should paint a grid of a different size than the global one
		[Tooltip("是否覆盖全局网格尺寸。开启后使用下方 GridWidth/GridHeight；关闭后使用生成器的全局尺寸范围")]
		public bool OverrideGridSize = false;
		/// the new value of the grid width
		[Tooltip("该图层覆盖后的网格宽度（仅 OverrideGridSize 开启时生效）")]
		[MMCondition("OverrideGridSize", true)]
		public int GridWidth = 50;
		/// the new value of the grid height
		[Tooltip("该图层覆盖后的网格高度（仅 OverrideGridSize 开启时生效）")]
		[MMCondition("OverrideGridSize", true)]
		public int GridHeight = 50;
        
		[Header("Method")] 
		/// the algorithm to use to generate this layer's grid
		[Tooltip("该图层网格生成算法：满的（全满或全空）；柏林（使用柏林噪声随机填充）；柏林球场（使用柏林噪声生成地表）；随机值走（从起点随机行走并刻出路径）；随机值避免步行者（随机行走并刻出路径）；小路（从起点沿指定方向挖出路径）；复制（另一个瓷砖地图复制从生成网格）。")]
		public MMTilemapGenerator.GenerateMethods GenerateMethod = MMTilemapGenerator.GenerateMethods.Perlin;
		/// if this is true, global seed won't be used for this layer
		[Tooltip("是否不使用全局种子。开启后该图层将改用自己的 Seed/RandomizeSeed 设置")]
		public bool DoNotUseGlobalSeed = false;
		/// whether or not to randomize this layer's seed when pressing Generate
		[Tooltip("每次点击 Generate 时是否随机该图层 Seed（仅 DoNotUseGlobalSeed 开启时生效）")]
		[MMCondition("DoNotUseGlobalSeed", true)]
		public bool RandomizeSeed = true;
		/// the dedicated seed of this layer, when not using the global one
		[Tooltip("该图层专用种子（仅 DoNotUseGlobalSeed 开启且 RandomizeSeed 关闭时稳定生效）")]
		[MMCondition("DoNotUseGlobalSeed", true)]
		public int Seed = 1;
        
		[Header("PostProcessing")]
		/// whether or not to smoothen the resulting grid, gets rid of spikes/isolated points
		[Tooltip("是否平滑结果网格，可减少尖刺/孤立点")]
		public bool Smooth = false;
		/// whether or not to invert the grid to get the opposite result (filled becomes empty, empty becomes filled)
		[Tooltip("是否反转网格结果（填充变空，空变填充）")]
		public bool InvertGrid = false;
		/// The selected fusion mode
		[Tooltip("图层融合模式：\n" +
		         "图层按从上到下融合（后处理的图层会覆盖先前结果）\n" +
		         "Normal：正常生成并覆盖\n" +
		         "NormalNoClear：生成但不先清空目标\n" +
		         "Intersect：仅保留与现有内容的交集\n" +
		         "Combine：将该图层结果叠加到目标\n" +
		         "Subtract：从目标中扣除该图层结果")]
		public FusionModes FusionMode = FusionModes.Normal;
        
		[Header("Settings")]
        
		// full
		/// in full mode, whether the grid should be full or empty
		[Tooltip("Full 模式下网格是全满还是全空")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.Full)]
		public bool FullGenerationFilled = true;
    
		// random
		/// in random mode, the percentage of the grid to fill
		[Tooltip("Random 模式下网格填充百分比")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.Random)]
		public int RandomFillPercentage = 50;
    
		// random walk ground 
		/// in random walk ground mode,the minimum height difference between two steps
		[Tooltip("Random Walk Ground 模式下，相邻两步的最小高度差")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkGround)]
		public int RandomWalkGroundMinHeightDifference = 1;
		/// in random walk ground mode,the maximum height difference between two steps 
		[Tooltip("Random Walk Ground 模式下，相邻两步的最大高度差")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkGround)]
		public int RandomWalkGroundMaxHeightDifference = 3;
		/// in random walk ground mode, the minimum distance that should remain flat
		[Tooltip("Random Walk Ground 模式下，保持平地的最小长度")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkGround)]
		public int RandomWalkGroundMinFlatDistance = 1;
		/// in random walk ground mode, the maximum distance that should remain flat
		[Tooltip("Random Walk Ground 模式下，保持平地的最大长度")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkGround)]
		public int RandomWalkGroundMaxFlatDistance = 3;
		/// in random walk ground mode, the maximum height of the tallest platfrom, from the bottom of the grid
		[Tooltip("Random Walk Ground 模式下，从网格底部计算的最高平台上限高度")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkGround)]
		public int RandomWalkGroundMaxHeight = 3;
        
		// random walk
		/// in random walk mode, the percentage of the map the walker should try filling
		[Tooltip("Random Walk 模式下，行走器尝试填充地图的百分比")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalk)]
		public int RandomWalkPercent = 50;
		/// in random walk mode,the point at which the walker starts, in grid coordinates
		[Tooltip("Random Walk 模式下，行走器的起点（网格坐标）")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalk)]
		public Vector2Int RandomWalkStartingPoint = Vector2Int.zero;
		/// in random walk mode, the max amount of iterations to run the random on 
		[Tooltip("随机值行走模式下最大迭代次数")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalk)]
		public int RandomWalkMaxIterations = 1500;
        
		// random walk avoider
		/// in random walk avoider mode, the percentage of the grid the walker should try filling
		[Tooltip("Random Walk Avoider 模式下，行走器尝试填充网格的百分比")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkAvoider)]
		public int RandomWalkAvoiderPercent = 50;
		/// in random walk avoider mode, the point in grid units at which the walker starts 
		[Tooltip("Random Walk Avoider 模式下，行走器起点（网格坐标）")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkAvoider)]
		public Vector2Int RandomWalkAvoiderStartingPoint = Vector2Int.zero;
		/// in random walk avoider mode, the tilemap containing the data the walker will try to avoid
		[Tooltip("Random Walk Avoider 模式下的障碍 Tilemap；行走器会尝试避开其中内容")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkAvoider)]
		public Tilemap RandomWalkAvoiderObstaclesTilemap;
		/// in random walk avoider mode,the distance at which the walker should try to stay away from obstacles
		[Tooltip("Random Walk Avoider 模式下与障碍保持的最小距离")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkAvoider)]
		public int RandomWalkAvoiderObstaclesDistance = 1;
		/// in random walk avoider mode,the max amount of iterations this algorithm will iterate on
		[Tooltip("随机值行走避免器模式下最大迭代次数")]
		[MMEnumCondition("GenerateMethod", (int)MMTilemapGenerator.GenerateMethods.RandomWalkAvoider)]
		public int RandomWalkAvoiderMaxIterations = 100;
        
		// path
		/// in path mode, the start position of the path
		[Tooltip("Path 模式下路径起点（网格坐标）")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public Vector2Int PathStartPosition = Vector2Int.zero;
		/// in path mode, the direction the path should follow
		[Tooltip("Path 模式下路径延展方向")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public MMGridGeneratorPath.Directions PathDirection = MMGridGeneratorPath.Directions.BottomToTop;
		/// in path mode, the minimum width of the path
		[Tooltip("Path 模式下路径最小宽度")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public int PathMinWidth = 2;
		/// in path mode, the maximum width of the path
		[Tooltip("Path 模式下路径最大宽度")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public int PathMaxWidth = 4;
		/// in path mode, the maximum number of units the path can change direction
		[Tooltip("Path 模式下每次改变方向前可连续前进的最大单位数")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public int PathDirectionChangeDistance = 2;
		/// in path mode, the chance (in percent) for the path to change width at every step
		[Tooltip("Path 模式下每一步改变路径宽度的概率（百分比）")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public int PathWidthChangePercentage = 50;
		/// in path mode, the chance percentage that the path will take a new direction
		[Tooltip("Path 模式下路径改变方向的概率（百分比）")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Path)]
		public int PathDirectionChangePercentage = 50;
        
		// copy
		/// in copy mode, the tilemap to copy
		[Tooltip("复制模式下要复制的来源 瓷砖地图")]
		[MMEnumCondition("GenerateMethod", (int) MMTilemapGenerator.GenerateMethods.Copy)]
		public Tilemap CopyTilemap;
    
		[Header("Bounds")] 
		/// whether or not to force a wall on the grid's top
		[Tooltip("是否在网格顶部强制生成边界墙")]
		public bool BoundsTop = false; 
		/// whether or not to force a wall on the grid's bottom
		[Tooltip("是否在网格底部强制生成边界墙")]
		public bool BoundsBottom = false; 
		/// whether or not to force a wall on the grid's left
		[Tooltip("是否在网格左侧强制生成边界墙")]
		public bool BoundsLeft = false; 
		/// whether or not to force a wall on the grid's right
		[Tooltip("是否在网格右侧强制生成边界墙")]
		public bool BoundsRight = false;

		/// <summary>
		/// A struct used to store safe spots dimensions
		/// </summary>
		[Serializable]
		public struct MMTilemapGeneratorLayerSafeSpot
		{
			public Vector2Int Start;
			public Vector2Int End;
		}

		[Header("Safe Spots")] 
		/// a list of "safe spots" : defined by their start and end coordinates, these areas will be left empty
		[Tooltip("安全区域列表（由起止坐标定义），这些区域会被强制留空")]
		public List<MMTilemapGeneratorLayerSafeSpot> SafeSpots;
        
		[HideInInspector]
		/// this is only used to initialize the default values in the inspector
		public bool Initialized = false;
        
		/// <summary>
		/// This method will set default values, because Unity.
		/// </summary>
		public virtual void SetDefaults()
		{
			if (!Initialized)
			{
				GridWidth = 50;
				GridHeight = 50;
				GenerateMethod = MMTilemapGenerator.GenerateMethods.Perlin;
				RandomizeSeed = true;
				DoNotUseGlobalSeed = false;
				FusionMode = FusionModes.Normal;
				Seed = 123456789;
				Smooth = false;
				InvertGrid = false;
				FullGenerationFilled = true;
				RandomFillPercentage = 50;
				RandomWalkGroundMinHeightDifference = 1;
				RandomWalkGroundMaxHeightDifference = 3;
				RandomWalkGroundMinFlatDistance = 1;
				RandomWalkGroundMaxFlatDistance = 3;
				RandomWalkGroundMaxHeight = 8;
				RandomWalkPercent = 50;
				RandomWalkStartingPoint = Vector2Int.zero;
				RandomWalkMaxIterations = 1500;
				PathMinWidth = 2;
				PathMaxWidth = 4;
				PathDirectionChangeDistance = 2;
				PathWidthChangePercentage = 50;
				PathDirectionChangePercentage = 50;
				RandomWalkAvoiderPercent = 50;
				RandomWalkAvoiderStartingPoint = Vector2Int.zero;
				RandomWalkAvoiderObstaclesTilemap = null;
				RandomWalkAvoiderObstaclesDistance = 1;
				RandomWalkAvoiderMaxIterations = 100;
				BoundsTop = false; 
				BoundsBottom = false; 
				BoundsLeft = false; 
				BoundsRight = false;
				PathStartPosition = Vector2Int.zero;
				PathDirection = MMGridGeneratorPath.Directions.BottomToTop;
				Initialized = true;
			}            
		}
		#endif
	}
}
